"$schema" = "./node_modules/wrangler/config-schema.json"

name = "kirinuki-search"
compatibility_date = "2026-05-21"
main = "./src/worker.ts"

[[routes]]
pattern = "kirinuki-search.nasubi.love/*"
zone_name = "nasubi.love"

[[services]]
binding = "SEARCH_SERVICE"
service = "yt-streamback"
remote = true

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[observability.logs]
enabled = false
invocation_logs = true
